apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-heavy-app-hpa
  namespace: marek-apps
spec:
  minReplicas: 1
  maxReplicas: 9
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-heavy-app-hpa
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: averageValue
        averageValue: 1500m
  - type: Resource
    resource:
      name: mameory
      target:
        type: averageValue
        averageValue: 300Mi    
