    - job_name: nginx-server-hpa
      scheme: http
      scrape_interval: 10s
      static_configs:
      - targets: ['reverse-proxy-hpa-metrics.marek-apps.svc:9113']
        labels:
          app: nginx-hpa
    - job_name: nginx-server-kmn
      scheme: http
      scrape_interval: 10s
      static_configs:
      - targets: ['reverse-proxy-kmn-metrics.marek-apps.svc:9113']
        labels:
          app: nginx-kmn
    - job_name: nginx-server-kral
      scheme: http
      scrape_interval: 10s
      static_configs:
      - targets: ['reverse-proxy-kral-metrics.marek-apps.svc:9113']
        labels:
          app: nginx-kral