apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-kral-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-kral
    envSourceContainerName: nginx
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  2
  maxReplicaCount:  7
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus-multicriterial-ral
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-multicriterial-ral-test
      query1: sum by (deployment) (container_cpu_usage_seconds_total{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
      query2: sum by (deployment) (container_memory_usage_bytes{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
      query3: sum by (deployment) (container_memory_usage_bytes{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
