apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-kral-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-kral
    envSourceContainerName: nginx
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  5
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus-multicriterial-ral
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-multicriterial-ral-test
      query1: absent(up{job="kube-state-metrics"} == 1)
      query2: absent(up{job="kube-state-metrics"} == 1)
      query3: absent(up{job="kube-state-metrics"} == 1)
      query4: count(container_memory_usage_bytes{namespace="marek-apps", deployment=~"nginx-server-.*",container="POD"})
