apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-heavy-app-kral-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          cpu-heavy-app-kral
    envSourceContainerName: cpu-heavy-app
  pollingInterval:  15
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  9
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus-multicriterial-ral
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-multicriterial-ral-test
      query1: sum (rate(container_cpu_usage_seconds_total{namespace="marek-apps", deployment="cpu-heavy-app-kral", container="cpu-heavy-app"}[30s]) * 1024) by (deployment)
      reservationLevel1: '1500.0'
      aspirationLevel1: '200.0'
      query2: sum (container_memory_usage_bytes{namespace="marek-apps", deployment="cpu-heavy-app-kral", container="cpu-heavy-app"} / 1024 / 1024) by (deployment)
      reservationLevel2: '400.0'
      aspirationLevel2: '100.0'
      query3: nginxplus_upstream_server_response_time
      reservationLevel3: '8000.0'
      aspirationLevel3: '3000.0'
      query4: absent(up{job="test"} == 1)
