apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-hpa-metrics
  namespace: marek-apps
spec:
  type: ClusterIP
  selector:
    app: reverse-proxy-hpa
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
