apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-kmn-metrics
  namespace: marek-apps
spec:
  type: ClusterIP
  selector:
    app: nginx-kmn
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
