apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-kmn
  namespace: marek-apps
spec:
  type: NodePort
  selector:
    app: nginx-kmn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31120
