apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-kral
  namespace: marek-apps
  annotations:
    prometheus.io/port: "9113"
    prometheus.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app: nginx-kral
  template:
    metadata:
      labels:
        app: nginx-kral
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
              cpu: "20m"
            limits:
              memory: "16Mi"
              cpu: "20m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.11.0'
          ports:
            - containerPort: 9113
          args:
            - '-nginx.scrape-uri=http://localhost/basic_status'
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config
