apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-kmn
  namespace: marek-apps
spec:
  type: NodePort
  selector:
    app: reverse-proxy-kmn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31121
