apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-hpa-metrics
  namespace: marek-apps
spec:
  type: ClusterIP
  selector:
    app: nginx-hpa
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
