apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-hpa
  namespace: marek-apps
spec:
  type: NodePort
  selector:
    app: nginx-hpa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110
