apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-kmn-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-kmn
    envSourceContainerName: nginx
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  4
  triggers:
  - type: prometheus-criterial-minkowski-norm
    metadata:
      serverAddress: http://prometheus-k8s.monitoring.svc:9090
      metricName: prometheus-multicriterial-minkowski-norm-test
      queryParam1: '1000'
      threshold1: '1'
      query1: sum by (pod) (container_cpu_system_seconds_total{pod="nginx-server-kmn-5cb88966c9-wz4xl"})
      queryParam2: '1000'
      threshold2: '1'
      query2: sum by (pod) (container_memory_usage_bytes{pod="nginx-server-kmn-5cb88966c9-wz4xl"})