apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-heavy-app-kmn-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          cpu-heavy-app-kmn
    envSourceContainerName: cpu-heavy-app
  pollingInterval:  15
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  9
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus-minkowski-norm
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-minkowski-norm-test
      numOfParams: '1'
      queryParam1: '5'
      query1: sum (rate(container_cpu_usage_seconds_total{namespace="marek-apps", deployment="cpu-heavy-app-kmn", container="cpu-heavy-app"}[30s]) * 1024) by (deployment)
      threshold1: '1500'
      queryParam2: '4'
      query2: sum (container_memory_usage_bytes{namespace="marek-apps", deployment="cpu-heavy-app-kmn", container="cpu-heavy-app"} / 1024 / 1024) by (deployment)
      threshold2: '200'
      queryParam3: '1'
      query3: scalar(nginxplus_upstream_server_response_time{job="reverse-proxy-kmn"})
      threshold3: '5000'
