apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-kmn-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-kmn
    envSourceContainerName: nginx
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  2
  maxReplicaCount:  4
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus-minkowski-norm
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-minkowski-norm-test
      numOfParams: '3'
      queryParam1: '1000'
      threshold1: '1'
      query1: sum by (deployment) (container_cpu_usage_seconds_total{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
      queryParam2: '1000'
      threshold2: '1'
      query2: sum by (deployment) (container_memory_usage_bytes{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
      queryParam3: '1000'
      threshold3: '1'
      query3: sum by (deployment) (container_memory_usage_bytes{namespace="marek-apps", deployment="nginx-server-kmn", container="nginx"})
