apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-server-kmn-keda
  namespace: marek-apps
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          nginx-server-kmn
    envSourceContainerName: nginx
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  4
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: prometheus-test
      query: absent(up{job="kube-state-metrics"} == 1)
      threshold: '1'
