apiVersion: v1
kind: Service
metadata:
  name: cpu-heavy-app-actuator-kral
  namespace: marek-apps
spec:
  type: ClusterIP
  selector:
    app: cpu-heavy-app-kral
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
