apiVersion: v1
kind: Service
metadata:
  name: cpu-heavy-app-kral
  namespace: marek-apps
spec:
  type: NodePort
  selector:
    app: cpu-heavy-app-kral
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31130
